# Não lembro pq fixei nessa versão
- name: vaulttec.zsh
  src: https://github.com/vaulttec/ansible-role-zsh.git
  version: 5b518747c6d3791e936dce678afa7

# fork that I sent PR and were not accepted
- name: mmacia.vim
  src: https://github.com/thiagogomesverissimo/ansible-vim.git
  version: master

- name: ansible-role-phpcs
  src: https://github.com/thiagogomesverissimo/ansible-role-phpcs
  version: get-composer-bin-dir-from-user

- src: geerlingguy.mysql
  version: 2.9.5

- src: geerlingguy.nodejs
  version: 5.0.0

- src: geerlingguy.php
  version: 3.7.0

- src: geerlingguy.php-versions
  version: 4.0.2

- src: geerlingguy.composer
  version: 1.7.6

- src: geerlingguy.firewall
  version: 2.4.2

- src: geerlingguy.docker
  version: 2.9.0

- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.java
  version: 1.9.7

- src: oefenweb.rstudio
  version: v2.2.8

- src: infOpen.locales
  version: master

- src: geerlingguy.ntp
  version: 1.6.4

- src: adriagalin.timezone
  version: 1.0.1

- src: geerlingguy.postgresql
  version: 2.0.1

- name: thiagogomesverissimo.vimspell
  src: https://github.com/thiagogomesverissimo/ansible-role-vimspell.git
  version: 1.0.0

- src: infOpen.vagrant
  version: 0.3.0

- src: zzet.rbenv
  version: 3.4.7

- src: geerlingguy.dotfiles
  version: 1.2.1

- src: gantsign.visual-studio-code
  version: 6.3.1

#- name: oefenweb.r
#  src: https://github.com/thiagogomesverissimo/ansible-r.git
#  version: debian9
