# Fork that I sent PR and were not accepted
- name: mmacia.vim
  src: https://github.com/thiagogomesverissimo/ansible-vim.git
  version: master
  
- name: vaulttec.zsh
  src: https://github.com/thiagogomesverissimo/ansible-role-zsh.git
  version: 1.0.0

# Comunidade

- src: geerlingguy.docker
  version: 8.0.0

- src: geerlingguy.pip
  version: 3.1.2

- src: infOpen.locales
  version: master

- name: thiagogomesverissimo.vimspell
  src: https://github.com/thiagogomesverissimo/ansible-role-vimspell.git
  version: master

- src: geerlingguy.dotfiles
  version: 1.2.1
