# Não lembro pq fixei nessa versão
- name: vaulttec.zsh
  src: https://github.com/vaulttec/ansible-role-zsh.git
  version: 5b518747c6d3791e936dce678afa7

# fork that I sent PR and were not accepted
- name: mmacia.vim
  src: https://github.com/thiagogomesverissimo/ansible-vim.git
  version: master

- src: geerlingguy.mysql
  version: 3.3.0

- src: geerlingguy.nodejs
  version: 5.0.0

- src: geerlingguy.php
  version: 3.7.0

- src: geerlingguy.php-versions
  version: 4.0.2

- src: geerlingguy.composer
  version: 1.9.0

- src: geerlingguy.firewall
  version: 2.4.2

- src: geerlingguy.docker
  version: 2.9.0

- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.java
  version: 1.9.7

- src: infOpen.locales
  version: master

- src: geerlingguy.ntp
  version: 1.6.4

- src: adriagalin.timezone
  version: 1.0.1

- name: thiagogomesverissimo.vimspell
  src: https://github.com/thiagogomesverissimo/ansible-role-vimspell.git
  version: 1.0.0

- src: geerlingguy.dotfiles
  version: 1.2.1

- src: gantsign.visual-studio-code
  version: 6.3.1
