- name: Install vim
  apt:
    name: vim
    state: latest 
    update_cache: yes

- name: vim dirs
  file:
    path: "{{item}}"
    recurse: yes
    state: directory
    owner: "{{workstation_user}}"
    group: "{{workstation_user}}"
  with_items:
    - "{{workstation_home}}/.vim/autoload/"
    - "{{workstation_home}}/.vim/bundle/"
    - "{{workstation_home}}/.vim/colors/"

- name: Download colors
  get_url:
    url: "{{ item.url }}"
    dest: "{{ workstation_home }}/.vim/colors/{{ item.name }}.vim"
    mode: 0440
  with_items:
    - { url: 'https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/vim/colors/Tomorrow-Night.vim', name: 'Tomorrow-Night'}

- composer:
    command: install
    working_dir: "{{workstation_home}}/.vim/bundle/phpactor"
    no_dev: no

- file:
    src: "{{workstation_home}}/.vim/bundle/phpactor/bin/phpactor"
    dest: /usr/local/bin/phpactor
    state: link

- lineinfile:
    path: "{{workstation_home}}/.vimrc"
    line: 'colorscheme Tomorrow-Night'

- lineinfile:
    path: "{{workstation_home}}/.vimrc"
    line: 'hi SpellBad ctermfg=red guifg=red'

- name: vim fix permission
  file:
    path: "{{workstation_home}}/.vim/"
    recurse: yes
    owner: "{{workstation_user}}"
    group: "{{workstation_user}}"
    mode: 0700
