- name: Install fdclone
  apt:
    name: fdclone
    state: latest 
    update_cache: yes

- name: clone fzf
  become_user: "{{ workstation_user}}"
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ workstation_home }}/.fzf"
    update: yes

- name: install fzf
  become_user: "{{ workstation_user}}"
  shell: "./install --all"
  args:
    chdir: "{{ workstation_home }}/.fzf"

- name: Template p10k.zsh
  copy:
    src: p10k.zsh
    dest: "{{ workstation_home }}/.p10k.zsh"
    owner: "{{workstation_user}}"
    group: "{{workstation_user}}"

- lineinfile:
    path: "{{ workstation_home }}/.zshrc"
    insertbefore: '^ZSH_THEME'
    line: 'export TERM="xterm-256color"'

- name: Download algs4
  get_url:
    url: "https://algs4.cs.princeton.edu/code/algs4.jar"
    dest: "{{ workstation_home }}/.algs4.jar"

- lineinfile:
    path: "{{ workstation_home }}/.zshrc"
    insertbefore: '^ZSH_THEME'
    line: 'export CLASSPATH=$CLASSPATH:~/.algs4.jar'

