---
- name: provision
  become: yes
  #  hosts: vagrant
  hosts: localhost

  vars:
    # global vars
    workstation_user: thiago
    workstation_home: /home/thiago

  tasks:
        
    # general packages
    - name: install general apt packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - tmux
          - dirmngr
          - sqlite3
          - zip
          - unzip
          - rar
          - unrar
          - git
          - curl
          - nfs-kernel-server # para vagrant

    # pip 3 packages
    - include_role:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
         - virtualenv
         - numpy
         - pandas
         - ipython
         - jupyter
         - matplotlib
         - pymysql

    # vim
    - include_role:
        name: mmacia.vim
      vars:
        vim_env: user
        vim_users:
          - "{{workstation_user}}"
        vimrc_recommended: false
        vim_plugins:
          - 'mattn/emmet-vim'
          - 'scrooloose/nerdtree'

    # vim spell
    - include_role:
        name: thiagogomesverissimo.vimspell
      vars:
        vimspell_home: "{{workstation_home}}"
        vimspell_user: "{{workstation_user}}"
        vimspell_languages:
          - pt
          - es
          - en

    # docker
    - include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - "{{workstation_user}}"
    
      # oh-my-zsh
    - include_role:
        name: vaulttec.zsh
      vars:
        zsh_users:
         - "{{workstation_user}}"
        zsh_ohmy_theme: "robbyrussell"
        zsh_ohmy_auto_update: true
        zsh_ohmy_plugins:
          - git
          - zsh-syntax-highlighting
          - zsh-autosuggestions
          - pass
          - tmux
          - vagrant
          - pip
        zsh_ohmy_custom_themes:
          - name: powerlevel10k
            repo: "https://github.com/romkatv/powerlevel10k.git"
          - name: spaceship
            repo: "https://github.com/spaceship-prompt/spaceship-prompt.git"


    # workstation
    - include_role:
        name: local.workstation
