---
- name: provision
  become: yes
#  hosts: vagrant
  hosts: localhost

  vars:

    # global vars
    workstation_user: thiago
    workstation_home: /home/thiago
    php_version: "7.3"
    php_default_version_debian: "{{php_version}}"
    php_use_managed_ini: false
    php_enable_apc: false
    php_enable_webserver: false
    php_packages_extra:
      - php{{ php_version }}-curl
      - php{{ php_version }}-ldap
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-pgsql
      - php{{ php_version }}-mysql
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-sybase

  tasks:

    # general packages
    - name: install general packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - tmux
          - dirmngr
          - sqlite3
          - zip
          - unzip
          - git

    # Configuração do timezone são paulo
    - include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    # locales como pt-br
    - include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    # ntp
    - include_role:
        name: ontic.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 'a.st1.ntp.br'
          - 'b.st1.ntp.br'

    # php versions
    - name: Instala PHP versions
      include_role:
        name: geerlingguy.php-versions

    # php
    - name: Instala PHP
      include_role:
        name: geerlingguy.php

    # drupal console
    - name: geerlingguy.drupal-console
      include_role:
        name: geerlingguy.drupal-console

    # drush
    - include_role:
        name: geerlingguy.drush
      vars:
        drush_launcher_version: 0.6.0

    # composer
    - include_role:
        name: geerlingguy.composer
      vars:
        composer_keep_updated: True
        composer_global_packages:
          - name: squizlabs/php_codesniffer 
          - name: drupal/coder
          - name: dealerdirect/phpcodesniffer-composer-installer
          - name: phpunit/phpunit
          - name: friendsofphp/php-cs-fixer
        composer_home_owner: "{{workstation_user}}"
        composer_home_group: "{{workstation_user}}"
        composer_project_path: "{{workstation_user}}/.composer/vendor/bin/"

    # phpcs
    - include_role:
        name: ansible-role-phpcs
      vars:
        phpcs_config_set:
          - 'encoding utf-8'
          - 'colors 1'
          - 'report_width 120'
          - 'tab_width 4'
          - 'installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer'
        phpcs_user: "{{workstation_user}}"

    # mysql
    - include_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_username: root
        mysql_root_password: master
        mysql_bind_address: '*'
        mysql_users:
          - name: master
            host: "%"
            password: master
            priv: "*.*:ALL,GRANT"

    # nodejs
    - include_role:
        name: geerlingguy.nodejs
      vars:
        nodejs_version: "10.x"
        nodejs_install_npm_user: "{{ workstation_user }}"
        nodejs_npm_global_packages:
          - name: yo
          - name: reveal
          - name: prez
          - name: generator-jhipster
          - name: gulp-cli
          - name: bower
          - name: generator-webapp
          - name: webpack
          - name: webpack-cli

    # firewall
    - include_role:
        name: geerlingguy.firewall
      vars:
        firewall_allowed_tcp_ports:
          - "22"
          - "80"
          - "3306"
          - "5432"

    # docker
    - include_role:
        name: geerlingguy.docker
      vars:
        docker_compose_version: 1.24.0
        docker_users:
          - "{{workstation_user}}"

    # pip
    - include_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - virtualenv
          - numpy
          - pandas
          - ipython
          - jupyter
          - matplotlib
          - hub

    # oh-my-zsh
    - include_role:
        name: vaulttec.zsh
      vars:
        zsh_users:
         - "{{workstation_user}}"
        zsh_ohmy_theme: "powerlevel9k/powerlevel9k"
        zsh_ohmy_auto_update: true
        zsh_ohmy_plugins:
          - git
          - git-flow
          - docker
          - zsh-syntax-highlighting
          - zsh-autosuggestions
          - pass
          - tmux
          - vagrant
          - pip
          - git-prompt
        zsh_ohmy_custom_themes:
          - name: powerlevel9k
            repo: "https://github.com/bhilburn/powerlevel9k.git"
          - name: spaceship
            repo: "https://github.com/denysdovhan/spaceship-prompt.git"

    # vim
    - include_role:
        name: mmacia.vim
      vars:
        vim_env: user
        vim_users:
          - "{{workstation_user}}"
        vimrc_recommended: false
        vim_plugins:
          - 'mattn/emmet-vim'
          - 'scrooloose/nerdtree'
          - 'adoy/vim-php-refactoring-toolbox'
          - 'stephpy/vim-php-cs-fixer'
          - 'sheerun/vim-polyglot'
          - 'Raimondi/delimitMate'
          - 'vim-scripts/MatchTag'
          - 'godlygeek/tabular'
          - 'majutsushi/tagbar'
          - 'editorconfig/editorconfig-vim'
          - 'altercation/vim-colors-solarized'
          - 'phpactor/phpactor'
          - 'artur-shaik/vim-javacomplete2'
          - 'airblade/vim-rooter'

    # java
    - include_role:
        name: geerlingguy.java

    # rbenv
    - include_role:
        name: zzet.rbenv
      vars:
        rbenv:
          env: user
          version: v1.0.0
          default_ruby: 2.5.1
          rubies:
            - version: 2.4.2
            - version: 2.5.1
        rbenv_users:
         - "{{ workstation_user }}"

    # vim spell
    - include_role:
        name: uspdev.vimspell
      vars:
        vimspell_home: "{{workstation_home}}"
        vimspell_user: "{{workstation_user}}"
        vimspell_languages:
          - pt
          - es
          - en

#    # postgresql
#    - include_role:
#        name: geerlingguy.postgresql
#      vars:
#        postgresql_locales:
#          - 'pt_BR.UTF-8'
#        postgresql_users:
#          - name: master
#            password: 'master'
#            encrypted: True
#            role_attr_flags: SUPERUSER
#            db: template1
#            port: 5432

#    # R
#    - include_role:
#        name: oefenweb.r
#      vars:
#        r_install_dev: true
#        r_install:
#          - "r-recommended"
#        r_packages:
#          - name: dplyr
#          - name: "davidcarslaw/openair"
#            type: github
#

    # workstation
    - include_role:
        name: local.workstation
